// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAOW3AY6IRkOa4peVCrtc5jQCma5WYmlQ',
    appId: '1:353230136867:web:604be0ee8572caa2543396',
    messagingSenderId: '353230136867',
    projectId: 'recipegenerator-d5e36',
    authDomain: 'recipegenerator-d5e36.firebaseapp.com',
    storageBucket: 'recipegenerator-d5e36.firebasestorage.app',
    measurementId: 'G-HWQNQ6R14D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtI5eF8yzWhLN7uAf1DDJBdAF71Q5HB_4',
    appId: '1:353230136867:android:98e623afe8ed6370543396',
    messagingSenderId: '353230136867',
    projectId: 'recipegenerator-d5e36',
    storageBucket: 'recipegenerator-d5e36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYKmtwCTd0pHHhrVfGf30dKJMpUwECGag',
    appId: '1:353230136867:ios:544d8cad9ce99e53543396',
    messagingSenderId: '353230136867',
    projectId: 'recipegenerator-d5e36',
    storageBucket: 'recipegenerator-d5e36.firebasestorage.app',
    iosBundleId: 'com.example.tyamo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYKmtwCTd0pHHhrVfGf30dKJMpUwECGag',
    appId: '1:353230136867:ios:544d8cad9ce99e53543396',
    messagingSenderId: '353230136867',
    projectId: 'recipegenerator-d5e36',
    storageBucket: 'recipegenerator-d5e36.firebasestorage.app',
    iosBundleId: 'com.example.tyamo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAOW3AY6IRkOa4peVCrtc5jQCma5WYmlQ',
    appId: '1:353230136867:web:96b111a20f02f905543396',
    messagingSenderId: '353230136867',
    projectId: 'recipegenerator-d5e36',
    authDomain: 'recipegenerator-d5e36.firebaseapp.com',
    storageBucket: 'recipegenerator-d5e36.firebasestorage.app',
    measurementId: 'G-TJND9EGLH6',
  );
}
